"""Add meal_menus table

Revision ID: 03001b041216
Revises: 96c00f245ec5
Create Date: 2025-04-25 15:20:04.701848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03001b041216'
down_revision: Union[str, None] = '96c00f245ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_menus',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("meal_type IN ('breakfast', 'lunch', 'snack')", name='mealmenu_type_check'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'meal_type', name='uq_mealmenu_date_type')
    )
    op.create_index(op.f('ix_meal_menus_date'), 'meal_menus', ['date'], unique=False)
    op.create_index(op.f('ix_meal_menus_meal_type'), 'meal_menus', ['meal_type'], unique=False)
    op.create_index('ix_mealmenu_date_type', 'meal_menus', ['date', 'meal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mealmenu_date_type', table_name='meal_menus')
    op.drop_index(op.f('ix_meal_menus_meal_type'), table_name='meal_menus')
    op.drop_index(op.f('ix_meal_menus_date'), table_name='meal_menus')
    op.drop_table('meal_menus')
    # ### end Alembic commands ###
