"""Add balance to child and create balance_transactions table

Revision ID: a04e75a0a80d
Revises: b5495c32909e
Create Date: 2025-05-10 15:08:23.915203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04e75a0a80d'
down_revision: Union[str, None] = 'b5495c32909e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('child_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('deposit', 'withdrawal', 'correction_plus', 'correction_minus', 'initial_balance')", name='transaction_type_check'),
    sa.CheckConstraint('amount > 0', name='transaction_amount_positive_check'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_transactions_child_id'), 'balance_transactions', ['child_id'], unique=False)
    op.create_index(op.f('ix_balance_transactions_transaction_date'), 'balance_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_balance_transactions_type'), 'balance_transactions', ['type'], unique=False)
    op.add_column('children', sa.Column('balance', sa.Numeric(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False))
    op.drop_constraint('uq_holidays_date', 'holidays', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_holidays_date', 'holidays', ['date'])
    op.drop_column('children', 'balance')
    op.drop_index(op.f('ix_balance_transactions_type'), table_name='balance_transactions')
    op.drop_index(op.f('ix_balance_transactions_transaction_date'), table_name='balance_transactions')
    op.drop_index(op.f('ix_balance_transactions_child_id'), table_name='balance_transactions')
    op.drop_table('balance_transactions')
    # ### end Alembic commands ###
