"""Add absence_type to attendance and add holidays table

Revision ID: a96e085ee388
Revises: 03001b041216
Create Date: 2025-05-05 16:20:53.064134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96e085ee388'
down_revision: Union[str, None] = '03001b041216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True, comment='Название праздника (необязательно)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=True)
    op.add_column('attendances', sa.Column('absence_type', sa.String(length=20), nullable=True, comment='Тип отсутствия (sick_leave, vacation, other)'))
    op.create_index('ix_attendance_absence_type', 'attendances', ['absence_type'], unique=False)
    op.create_index(op.f('ix_attendances_absence_type'), 'attendances', ['absence_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendances_absence_type'), table_name='attendances')
    op.drop_index('ix_attendance_absence_type', table_name='attendances')
    op.drop_column('attendances', 'absence_type')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###
