"""add_post_and_media_tables

Revision ID: c5b752cd10f3
Revises: a04e75a0a80d
Create Date: 2025-05-12 13:16:56.985377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5b752cd10f3'
down_revision: Union[str, None] = 'a04e75a0a80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('thumbnail_path', sa.String(length=512), nullable=True))
    op.add_column('media', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('media', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('media', sa.Column('uploaded_by_id', sa.BigInteger(), nullable=True))
    op.add_column('media', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('media', 'post_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('media', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.drop_index('ix_media_group_id', table_name='media')
    op.drop_index('ix_media_uploaded_by', table_name='media')
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_unique_constraint(None, 'media', ['thumbnail_path'])
    op.drop_constraint('media_uploaded_by_fkey', 'media', type_='foreignkey')
    op.drop_constraint('media_group_id_fkey', 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'users', ['uploaded_by_id'], ['id'], ondelete='SET NULL')
    op.drop_column('media', 'updated_at')
    op.drop_column('media', 'group_id')
    op.drop_column('media', 'uploaded_by')
    op.drop_column('media', 'upload_date')
    op.drop_column('media', 'description')
    op.add_column('posts', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    op.alter_column('posts', 'text_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('posts', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index('ix_posts_author_id', table_name='posts')
    op.drop_index('ix_posts_created_at', table_name='posts')
    op.drop_index('ix_posts_group_id', table_name='posts')
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.drop_constraint('posts_author_id_fkey', 'posts', type_='foreignkey')
    op.drop_constraint('posts_group_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_column('posts', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_group_id_fkey', 'posts', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('posts_author_id_fkey', 'posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.create_index('ix_posts_group_id', 'posts', ['group_id'], unique=False)
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('ix_posts_author_id', 'posts', ['author_id'], unique=False)
    op.alter_column('posts', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('posts', 'text_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('posts', 'is_pinned')
    op.drop_column('posts', 'title')
    op.add_column('media', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('media', sa.Column('upload_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('media', sa.Column('uploaded_by', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('media', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('media', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key('media_group_id_fkey', 'media', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('media_uploaded_by_fkey', 'media', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'media', type_='unique')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.create_index('ix_media_uploaded_by', 'media', ['uploaded_by'], unique=False)
    op.create_index('ix_media_group_id', 'media', ['group_id'], unique=False)
    op.alter_column('media', 'file_path',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('media', 'post_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('media', 'uploaded_at')
    op.drop_column('media', 'uploaded_by_id')
    op.drop_column('media', 'mime_type')
    op.drop_column('media', 'original_filename')
    op.drop_column('media', 'thumbnail_path')
    # ### end Alembic commands ###
