"""add_global_notifications_table

Revision ID: f9da1f247cd1
Revises: 002881f37082
Create Date: 2025-05-12 18:02:20.189683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9da1f247cd1'
down_revision: Union[str, None] = '002881f37082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('author_id', sa.BigInteger(), nullable=True))
    op.add_column('notifications', sa.Column('audience', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_notifications_audience'), 'notifications', ['audience'], unique=False)
    op.create_index(op.f('ix_notifications_author_id'), 'notifications', ['author_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_author_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_audience'), table_name='notifications')
    op.drop_column('notifications', 'audience')
    op.drop_column('notifications', 'author_id')
    # ### end Alembic commands ###
